### ISSUE TITLE
IServiceProvider gets disposed

### ISSUE THREAD

**Issue by weng271190436** [unitycontainer/microsoft-dependency-injection#48] opened 2019-06-17 22:42 UTC
If I use Unity as my default DI container (by UseUnityServiceProvider()) and I call Url.Link() in a controller action twice, it is going to say:
System.ObjectDisposedException: 'Cannot access a disposed object. Object name: 'IServiceProvider'.'

I have a simple repro here: https://github.com/weng271190436/unityrepro/blob/master/WebApplication1/Controllers/ValuesController.cs

Start the .NET Core 2.2 web application.
If you hit localhost:5001/api/values for the first time, you will get a response.
If you hit that url the second time, you will see the ObjectDisposedException error.

**Comment by Jeromino** [comment] 2019-06-18 10:00
This is a [known issue](https://github.com/unitycontainer/microsoft-dependency-injection/issues/40) that is still open.

**Comment by weng271190436** [comment] 2019-06-18 23:07
I thought that version 5.10.2 is supposed to work around this problem? My simple repro is using 5.10.2 but it still hits this problem.

**Comment by ENikS** [comment] 2019-06-18 23:10
5.10.1 has workaround

Closing as duplicate of #40

**Closed by ENikS** 2019-06-18 23:10 UTC

**Comment by adrianpetrescu** [comment] 2019-07-03 06:36
@ENikS Indeed, using 5.10.1, you can no longer repro this issue but if you are using version 5.10.1 together with any version of Unity.Interception you ASP.NetCore fails starting. I mean when you use .UseUnityServiceProvider(). Is this also a known issue?

**Comment by adrianpetrescu** [comment] 2019-07-03 10:18
In the end I managed troubleshooting this downgrading Unity.Interception to 5.10.0
