### ISSUE TITLE
Missing resolution error details in ServiceProvider

### ISSUE THREAD

**Issue by carmeloanthony015** [unitycontainer/microsoft-dependency-injection#60] opened 2019-11-11 15:00 UTC
When, for example, we have an error during the resolution of a Controller constructor, we receive a very generic error message 

> Unable to resolve service for type Type2 while attempting to activate Type1

The error could be in a following resolution, but we'll never know...
I noticed that at [line 37 of ServiceProvider](https://github.com/unitycontainer/microsoft-dependency-injection/blob/8a16285e9ec72078ee97d1b9880feaa11a52627b/src/ServiceProvider.cs#L37) class, the exceptions thrown by `_container.Resolve` are "suppressed" and it just returns null. I think that throwing the exception here would give the user much more details about the error. Is this a good idea or is there a specific reason behind the particular exception handling in use currently?

**Comment by Jeromino** [comment] 2019-11-11 15:09
We should definitely not swallow thrown exceptions to return null because exceptions are not meant to control the execution flow but it is legitimate to return null in IServiceProvider.GetService because there is another IServiceProvider.GetRequiredService extension that can't return null.

This issue is a duplicate of [#53](https://github.com/unitycontainer/microsoft-dependency-injection/issues/53)  though.

**Comment by carmeloanthony015** [comment] 2019-11-11 15:24
Maybe I'm not getting entirely your answer, but MVC just uses IServiceProvider.GetService to invoke controllers' constructors, so I don't know how could I call IServiceProvider.GetRequiredService

**Comment by Jeromino** [comment] 2019-11-11 15:44
It looks like the ISupportRequiredService implementation is optional because it still calls GetService to throw an explicit exception when it can't resolve the requested type.

Otherwise I'm not sure about the MVC integration but there must be a way to customize how the resolution is done.

**Comment by carmeloanthony015** [comment] 2019-11-11 15:56
It's optional, but if not implemented we get a generic exception, not the verbose Unity logging. Considered this, even if we find a way to customize MVC integration, the issue would still not be resolved

**Comment by Jeromino** [comment] 2019-11-11 16:09
That's why there is still an [open issue for this bug](https://github.com/unitycontainer/microsoft-dependency-injection/issues/53).

I was just mentioning it can be legitimate to return null in GetRequiredService but it should throw an explicit exception with diagnostic details if the service is registered but the resolution fails because of another sub dependency that can't be resolved.

**Comment by ENikS** [comment] 2019-12-06 06:05
Duplicate of #53

**Closed by ENikS** 2019-12-06 06:05 UTC
