### ISSUE TITLE
Exception on startup when using UseUnityServiceProvider in 5.10.3

### ISSUE THREAD

**Issue by ben-wallis** [unitycontainer/microsoft-dependency-injection#44] opened 2019-04-26 11:51 UTC
Unity 5.10.3 seems to have broken the `Unity.Microsoft.DependencyInjection` integration when using ASP.NET Core - attempting to start a server with the `UseUnityServiceProvider` extension like so:

    WebHost.CreateDefaultBuilder()                                                                                             
    .UseUnityServiceProvider(unityContainer)                                                                                             
    .UseStartup<Startup>();

 results in the following exception on startup:

`No service for type 'Microsoft.Extensions.Logging.ILogger1[Microsoft.AspNetCore.Hosting.Internal.WebHost]' has been registered`

Rolling back to 5.10.2 resolved the issue

**Comment by BillKrat** [comment] 2019-04-28 23:30
With a minor update I got it working with the latest version of Unity and VS2019 Preview.   I blog the solution here => http://www.adventuresontheedge.net/admin/app/editor/editpost.cshtml?id=b0f700ee-f828-45c4-a486-1b5304a18be7

**Comment by StuffOfInterest** [comment] 2019-05-03 11:21
I ran into this as well.  For me, it happened with version 5.10.2 of both `Unity.Microsoft.DependencyInjection` and `Unity.Containers`.  When the app starts I get an `ObjectDisposedException` for `IServiceProvider`.  Reverting both packages back to 5.10.1 fixes it.  This was running in an ASP.NET Core 2.2 application.

**Comment by ENikS** [comment] 2019-05-04 14:15
@BillKrat 
Would you like to help with the official Unity example and perhaps create a descent documentation for it?

**Comment by ENikS** [comment] 2019-05-04 14:17
This is a duplicate of [this issue](https://github.com/unitycontainer/microsoft-dependency-injection/issues/40)

**Closed by ENikS** 2019-05-04 14:17 UTC

**Comment by BillKrat** [comment] 2019-05-05 03:46
@ENikS, I’d be interested.  I’m in the process of standing up an ASP.NET Core 3 framework that is dependent on unity.  It demonstrates constructor and setter injection.  Going to start TDD on it and will follow up with UML.   The concept being no C# code in the web app project and business / data layers can be swapped out.  It will be a reusable composite framework.

Cool thing is .Net Core 3.0 projects can reference .Net Standard projects, I.e. I can access a EF context which otherwise wouldn’t be available.

**Comment by BillKrat** [comment] 2019-05-07 11:25
@ENikS, I completed a [tutorial video](http://www.adventuresontheedge.net/post/2019/05/07/created-vs2019-asp-net-core-3-w-angular-application-using-unity) on how to use Unity IOC to swap out data access layers on an ASP.NET Core 3 w/Angular application.   

So that I can reach a larger audience, I'm going to submit an article proposal to MSDN (and if they are not interested Visual Studio magazine).   I'll create the article as a blog so that in the event I have no interested publishers I can publish it on my blog.    If you're interested in seeing the article [as I progress] please send me an email with an account name and password and I'll get you set up on http://AdventuresOnTheEdge.net.
